name: Deploy Webodle Dev
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-path: dist
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 20.x

          
      - run: npm ci
      - run: npm run build


        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Setup SSH and Deploy via rsync with rollback
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          LIVE_DIR="/home/$SSH_USERNAME/staging"

          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # Test SSH connection
          ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 $SSH_USERNAME@$SERVER_IP exit


          # Deploy new files
          rsync -avz --delete --exclude=".htaccess" -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=accept-new" dist/ $SSH_USERNAME@$SERVER_IP:$LIVE_DIR
          echo "Deployment complete."


